### ISSUE TITLE
GSSOC'24 (Update the Documentation of Swagger UI)

### ISSUE THREAD

**Issue by sujanMidatani7** [foss42/api#10]
Hey @ashitaprasad I want to update the swagger documentation of api endpoints, please assign me that I will do that

**Comment by hasmithagunda123** [comment]
I want to update the documentation. I m good at writing it please assign it to me

**Comment by ashitaprasad** [comment]
@sujanMidatani7 @hasmithagunda123 @akshatsharma2407 Send across a sample PR so that we can review your approach.

**Comment by ashitaprasad** [comment]
Also read - https://github.com/foss42/api/blob/main/CONTRIBUTING.md
