### ISSUE TITLE
Add the steps to build this project, so that contributors can easily work on this without wasting the time on figuring out that

### ISSUE THREAD

**Issue by SAISUPRIYAPAVARALA** [foss42/api#11]

**Comment by Jashwanth05** [comment]
Please assign this task , as I have lot of knowledge regarding API's it would be cake walk for me.

**Comment by yashika-ishi** [comment]
Good Evening, kindly assign this task to me, as I'm well experienced with python and API's.

**Comment by Shambhavee11** [comment]
Good Afternoon @SAISUPRIYAPAVARALA ,
I would like to explore this by understanding, learning all about this project. Kindly, assign me this task.

**Comment by ashitaprasad** [comment]
@SAISUPRIYAPAVARALA @Jashwanth05 @yashika-ishi @Shambhavee11 
The Readme and Contributing guide have been updated. Please go through it and follow all steps in the process that is mentioned.
