### ISSUE TITLE
Add a Learn.md

### ISSUE THREAD

**Issue by thakurboy004** [foss42/api#13]
Hi, I would like to point out that the readme of this repository does not give sufficient insight into the project and people like myself feel a bit confused regarding what and how should we contribute to this project, to avoid that, my suggestion would be to add a Learn.md file to give more insight into the whole structure of this repository and also to guide them throughout the whole procedure to contribute to this repository.
I would be glad to resolve this issue myself if it is assigned to me, and @ashitaprasad please add appropriate tags to this issue regarding GSSoC'24

**Comment by animator** [comment]
The project gives sufficient details. 
You need to go through Swagger docs (https://api.apidash.dev/docs) and the Contributing guide.
