### ISSUE TITLE
Providing Detailed Error instead of common error

### ISSUE THREAD

**Issue by atishayj2202** [foss42/api#15]
There should be a specific error for each not ```Internal Server Error``` even if input was invalid.

It should be something like invalid input or data not found.

This was seen in ```Country Endpoints```

**Comment by animator** [comment]
Send an example PR for review solving this issue.

**Comment by atishayj2202** [comment]
ok

**Comment by atishayj2202** [comment]
I am in GSSOC.
I have made branch #27
