### ISSUE TITLE
Add a PUT API

### ISSUE THREAD

**Issue by animator** [foss42/api#16]
In the route [routes/io](https://github.com/foss42/api/tree/main/src/routes), add a new API which can be used to test HTTP `PUT` method.

This issue will be assigned only after you send across a working PR.

**Comment by GANGSTER0910** [comment]
I want to work on this please assign me

**Comment by GANGSTER0910** [comment]
What exactly should I do in put request in this??

**Comment by tejaswini4996** [comment]
I would like to work on this issue

**Comment by YashAPro1** [comment]
Will you please assign me this, I really want to make it one of my first PRs under GSSOC - 24
I am a GSSOC 24 Contributor
