### ISSUE TITLE
Resolve Naming Conflict with Built-in io Module

### ISSUE THREAD

**Issue by deepashri30** [foss42/api#23]
I encountered an issue while trying to run the FastAPI application named **io.py**.  in routes/io
The error message indicates that Uvicorn cannot find the io_router attribute in the io module, which is likely due to a naming conflict with the built-in io module from the Python standard library.
To resolve this issue, we need to rename the FastAPI application file from **io.py** to something else, for example, app.py, to avoid the naming conflict with the built-in io module.

**Comment by animator** [comment]
Have you followed the instructions provided [here](https://github.com/foss42/api/blob/main/CONTRIBUTING.md#setting-up-dev-environment). We have not noticed any conflicts.
Raise a new issue with video recording showing the steps and conflict.
