### ISSUE TITLE
weather forecast api

### ISSUE THREAD

**Issue by merciajeno** [foss42/api#34]
This api is built using flask framework

**Comment by AashishKumar-3002** [comment]
Hey is this issue available. If yes, I can work on it @animator

**Comment by AashishKumar-3002** [comment]
Hey @animator, I and @merciajeno can work on this together. Can you assign this issue to me as well

**Comment by animator** [comment]
This won't be possible without using an external API and as this is an open source API project.
You are not allowed to use any external API.

**Comment by AashishKumar-3002** [comment]
Oh, thanks for informing. But I came across this repo https://github.com/open-meteo/open-meteo and its open source. is it not usable or allowed
