### ISSUE TITLE
Facial Recognition API

### ISSUE THREAD

**Issue by Raghucharan16** [foss42/api#39]
Deepface is a lightweight [face recognition](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/) and facial attribute analysis ([age](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), [gender](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), [emotion](https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/) and [race](https://sefiks.com/2019/11/11/race-and-ethnicity-prediction-in-keras/)) framework for python. It is a hybrid face recognition framework wrapping state-of-the-art models: [VGG-Face](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/), [FaceNet](https://sefiks.com/2018/09/03/face-recognition-with-facenet-in-keras/), [OpenFace](https://sefiks.com/2019/07/21/face-recognition-with-openface-in-keras/), [DeepFace](https://sefiks.com/2020/02/17/face-recognition-with-facebook-deepface-in-keras/), [DeepID](https://sefiks.com/2020/06/16/face-recognition-with-deepid-in-keras/), [ArcFace](https://sefiks.com/2020/12/14/deep-face-recognition-with-arcface-in-keras-and-python/), [Dlib](https://sefiks.com/2020/07/11/face-recognition-with-dlib-in-python/), SFace and GhostFaceNet.

Experiments show that human beings have 97.53% accuracy on facial recognition tasks whereas those models already reached and passed that accuracy level.Deepface is a lightweight [face recognition](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/) and facial attribute analysis ([age](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), [gender](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), [emotion](https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/) and [race](https://sefiks.com/2019/11/11/race-and-ethnicity-prediction-in-keras/)) framework for python. It is a hybrid face recognition framework wrapping state-of-the-art models: [VGG-Face](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/), [FaceNet](https://sefiks.com/2018/09/03/face-recognition-with-facenet-in-keras/), [OpenFace](https://sefiks.com/2019/07/21/face-recognition-with-openface-in-keras/), [DeepFace](https://sefiks.com/2020/02/17/face-recognition-with-facebook-deepface-in-keras/), [DeepID](https://sefiks.com/2020/06/16/face-recognition-with-deepid-in-keras/), [ArcFace](https://sefiks.com/2020/12/14/deep-face-recognition-with-arcface-in-keras-and-python/), [Dlib](https://sefiks.com/2020/07/11/face-recognition-with-dlib-in-python/), SFace and GhostFaceNet.

Experiments show that human beings have 97.53% accuracy on facial recognition tasks whereas those models already reached and passed that accuracy level.Deepface is a lightweight [face recognition](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/) and facial attribute analysis ([age](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), [gender](https://sefiks.com/2019/02/13/apparent-age-and-gender-prediction-in-keras/), [emotion](https://sefiks.com/2018/01/01/facial-expression-recognition-with-keras/) and [race](https://sefiks.com/2019/11/11/race-and-ethnicity-prediction-in-keras/)) framework for python. It is a hybrid face recognition framework wrapping state-of-the-art models: [VGG-Face](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/), [FaceNet](https://sefiks.com/2018/09/03/face-recognition-with-facenet-in-keras/), [OpenFace](https://sefiks.com/2019/07/21/face-recognition-with-openface-in-keras/), [DeepFace](https://sefiks.com/2020/02/17/face-recognition-with-facebook-deepface-in-keras/), [DeepID](https://sefiks.com/2020/06/16/face-recognition-with-deepid-in-keras/), [ArcFace](https://sefiks.com/2020/12/14/deep-face-recognition-with-arcface-in-keras-and-python/), [Dlib](https://sefiks.com/2020/07/11/face-recognition-with-dlib-in-python/), SFace and GhostFaceNet.

Experiments show that human beings have 97.53% accuracy on facial recognition tasks whereas those models already reached and passed that accuracy level.

This is not solely my work and it is being developed by @serengil and All credits go to him. I thought having an API for face related tasks such as [detection,recognition,facial analysis ->{age,race,gender,emotion}] would benefit the community and wanted to add it here.

**Comment by animator** [comment]
Send across a PR so that we can evaluate the approach.

**Comment by Raghucharan16** [comment]
Ok cool will do that. Even though the framework is not developed by me, i thought it would be helpful to be having here under api's repo.
