### ISSUE TITLE
[FEATURE]: Containerize the application

### ISSUE THREAD

**Issue by rohansen856** [foss42/api#51]
### Describe the feature

This app uses a specific version of python. So, it may not work on everybody's device. Containerizing the application using docker would make it easier and more developer friendly.
Please assign me this issue under GSSOC'24

![image](https://github.com/Clueless-Community/scrape-up/assets/108976786/16139e17-7c7d-479c-88dd-c8eb45a2582a)

**Comment by ashitaprasad** [comment]
Read the contributing guide properly to learn what kind of contributions this project is open to.
