### ISSUE TITLE
Workflow for auto commenting an issue creation

### ISSUE THREAD

**Issue by Asymtode712** [foss42/api#53]
This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue under gssoc'24

**Comment by ashitaprasad** [comment]
Please read the contributing guide and create a valid issue.
