### ISSUE TITLE
Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [foss42/api#54]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue under gssoc'24

**Comment by ashitaprasad** [comment]
Please read the contributing guide and create a valid issue.
