### ISSUE TITLE
Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [foss42/api#55]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue under gssoc'24

**Comment by ashitaprasad** [comment]
Please read the contributing guide and create a valid issue.
