### ISSUE TITLE
Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [foss42/api#56]
This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue under gssoc'24

**Comment by ashitaprasad** [comment]
Please read the contributing guide and create a valid issue.
