### ISSUE TITLE
Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [foss42/api#57]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue under gssoc'24

**Comment by ashitaprasad** [comment]
Please read the contributing guide and create a valid issue.
