### ISSUE TITLE
Add a Pull Request Template

### ISSUE THREAD

**Issue by Asymtode712** [foss42/api#58]
The solution is to implement a standardized pull request template. This template should include sections that prompt the author to provide essential information, such as:

A brief description of the changes.
The issue or feature being addressed (linked to relevant issue tracker entries).
Screenshots or GIFs (if the changes include UI modifications).
Checklist for confirming code adheres to coding standards, tests are added/updated, and documentation is updated.

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue under gssoc'24

**Comment by ashitaprasad** [comment]
Please read the contributing guide and create a valid issue.
