### ISSUE TITLE
add ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by gatlanagaprasanna** [foss42/api#60]
issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature.

We recommend creating a “Report Bug” and “Feature Request” issue template.

**Comment by gatlanagaprasanna** [comment]
kindly assign this issue to me under GSSOC'24

**Comment by ashitaprasad** [comment]
Please go through the contributing guide and raise a valid issue.
