### ISSUE TITLE
Missing LEARN.md file 

### ISSUE THREAD

**Issue by Meetjain1** [foss42/api#65]
Learn.md file is missing in our current repository 
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository.

@ashitaprasad assign this issue to me I will add it.

I am working under gssoc

**Comment by ashitaprasad** [comment]
Please go through the contributing guide to understand the project requirements and then raise a valid issue.
